import { Component }    from '@angular/core'; // Gain access to the Component features of Angular
// Gain access to the ProductMenu component features of the app
import { ProductMenuComponent } from './components/product-menu/product-menu.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ProductMenuComponent],  // Tell Angular you are using the ProductMenu component features
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {  
  // title = 'practice-assessment-5-Frank'; // generated by Angular - unused in this version
}
